Images:
- SourceImage: banzaicloud/logging-operator
  Tags:
  - 3.6.0
  - 3.7.0
  - 3.7.3
  - 3.8.0
  - 3.8.2
  - 3.9.0
  TargetImageName: banzaicloud-logging-operator
- SourceImage: banzaicloud/logging-operator
  Tags:
  - 3.10.0
  - 3.12.0
  - 3.9.0
  - 3.9.4
  - 3.9.5
- SourceImage: docker.io/test-org/test-image-2
  Tags:
  - v2.3.4
  - v4.50.6
  - v40.5.6
- SourceImage: fluent/fluent-bit
  Tags:
  - windows-2019-3.1.8
  - windows-2022-3.1.8
  TargetImageName: fluent-bit
- SourceImage: fluent/fluent-bit
  Tags:
  - 1.5.4
  - 1.5.4-debug
  - 1.6.1
  - 1.6.1-debug
  - 1.6.10
  - 1.6.10-debug
  - 1.6.4
  - 1.6.4-debug
  - 1.8.5-debug
  TargetImageName: fluent-fluent-bit
- SourceImage: fluent/fluent-bit
  Tags:
  - 1.6.10
  - 1.6.10-debug
  - 1.7.4
  - 1.7.4-debug
  - 1.7.9
  - 1.7.9-debug
  - 1.8.15
  - 1.8.15-debug
  - 1.8.5
  - 1.8.5-debug
  - 1.8.7
  - 1.8.7-debug
  - 1.8.8
  - 1.8.8-debug
  - 1.8.9
  - 1.8.9-debug
  - 1.9.3
  - 1.9.3-debug
  - 1.9.5
  - 1.9.5-debug
  - 2.2.0
  - 2.2.0-debug
  - 3.0.4
  - 3.0.4-debug
  - 3.1.8
  - 3.1.8-debug
- SourceImage: ghcr.io/kube-logging/config-reloader
  Tags:
  - v0.0.5
  - v0.0.6
- SourceImage: test-org/test-image
  Tags:
  - v1.2.3
  - v2.3.4
Repositories:
- BaseUrl: docker.io/rancher
  Password: '{{ env "DOCKER_PASSWORD" }}'
  Registry: docker.io
  Target: true
  Username: '{{ env "DOCKER_USERNAME" }}'
- BaseUrl: dp.apps.rancher.io/containers
  Password: '{{ env "APPCO_PASSWORD" }}'
  Registry: dp.apps.rancher.io
  Target: false
  Username: '{{ env "APPCO_USERNAME" }}'
- BaseUrl: registry.suse.com/rancher
  Password: '{{ env "PRIME_PASSWORD" }}'
  Registry: registry.suse.com
  Target: true
  Username: '{{ env "PRIME_USERNAME" }}'
