Images:
- SourceImage: docker.io/test-org/test-image-2
  Tags:
  - v2.3.4
  - v4.50.6
  - v40.5.6
- SourceImage: ghcr.io/kube-logging/config-reloader
  Tags:
  - v0.0.5
  - v0.0.6
- SourceImage: test-org/test-image
  Tags:
  - v1.2.3
  - v2.3.4
Repositories:
- BaseUrl: docker.io/rancher
  Password: '{{ env "DOCKER_PASSWORD" }}'
  Registry: docker.io
  Target: true
  Username: '{{ env "DOCKER_USERNAME" }}'
- BaseUrl: dp.apps.rancher.io/containers
  Password: '{{ env "APPCO_PASSWORD" }}'
  Registry: dp.apps.rancher.io
  Target: false
  Username: '{{ env "APPCO_USERNAME" }}'
- BaseUrl: registry.suse.com/rancher
  Password: '{{ env "PRIME_PASSWORD" }}'
  Registry: registry.suse.com
  Target: true
  Username: '{{ env "PRIME_USERNAME" }}'
